const express = require("express")
const app = express()
const dotenv = require("dotenv")
const addUser = require("./api/addUser/addUser")
const addPosts = require("./api/addPosts/addPosts")
const userPosts = require("./api/userPosts/userPosts")
const removePostList = require("./api/deletePost/removePost")
const userList = require("./api/userLists/users")
const userDetailPost = require("./api/userPostDetail/userDetailPost")
const postLists = require("./api/postLists/postList")
dotenv.config()
const cors = require("cors")
const port = process.env.PORT
app.listen(port, () => {
 console.log(`Server is running on port ${port}`)
})
app.use(express.json())
app.use(cors())
app.post("/user/add", addUser)
app.post("/post/add", addPosts)
app.get("/post/lists", postLists)
app.delete("/post/:postId", removePostList)
app.get("/user/lists", userList)
app.get("/user/posts", userPosts)
app.get("/user/post/detail/:userId", userDetailPost)