const express = require("express")
const app = express()
const dotenv = require("dotenv")
const addUser = require("./api/addUser/addUser")
const addPosts = require("./api/addPosts/addPosts")
const userPosts = require("./api/userPosts/userPosts")
const removeUserPosts = require("./api/deleteUserPosts/removeUserPosts")
const userList = require("./api/userLists/users")
const userDetailPost = require("./api/userPostDetail/userDetailPost")
dotenv.config()
const cors = require("cors")
const port = process.env.PORT
app.listen(port, () => {
 console.log(`Server is running on port ${port}`)
})
app.use(express.json())
app.use(cors())
app.post("/user/add", addUser)
app.post("/post/add", addPosts)
app.get("/user/lists", userList)
app.get("/user/posts", userPosts)
app.get("/user/post/detail/:userId", userDetailPost)
app.delete("/user/posts/:userId", removeUserPosts)